services:
  - type: web
    name: 7c-sinif-sohbet
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: 7c-db
          property: connectionString
      - key: ADMIN_SCHOOL_NO
        value: "90"
      - key: ADMIN_NAME
        value: "Muhammet Eymen Battal"
      - key: ADMIN_PASSWORD
        value: "Admin90"

databases:
  - name: 7c-db
    databaseName: school_chat
    user: school_user
    plan: free
