services:
  - type: web
    name: hava-durumu-uygulamasi
    runtime: python
    region: frankfurt
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn havadurumudeneme:app
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_gOV9pRWXP0KZ@ep-damp-band-adaemlf8-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: SECRET_KEY
        generateValue: true
      - key: WEATHER_API_KEY
        value: 11fd2f3a86a94ff5a52185939260203
      - key: TIME_API_KEY
        value: a33a0d8c690e4274ab5356b49247a66b
      - key: OPENROUTER_API_KEY
        value: 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
