services:
  - type: web
    name: hava-durumu-uygulamasi
    runtime: python
    region: frankfurt
    plan: free
    buildCommand: | 
      python3.11 -m venv venv
      source venv/bin/activate
      python3.11 -m pip install --upgrade pip
      python3.11 -m pip install -r requirements.txt
    startCommand: |
      source venv/bin/activate
      gunicorn havadurumudeneme:app
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_gOV9pRWXP0KZ@ep-damp-band-adaemlf8-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
